version: '3.3'

services:
 mysql-docker-container:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  container_name : mysql-docker-container
  restart: always
  environment:
   MYSQL_DATABASE: 'docker_db'
   # So you don't have to use root, but you can if you like
   MYSQL_USER: 'user'
   # You can use whatever password you like
   MYSQL_PASSWORD: 'mysql'
   # Password for root access
   MYSQL_ROOT_PASSWORD: 'mysql'
  ports:
   # <Port exposed> : < MySQL Port running inside container>
   - '3306:3306'
  expose:
   # Opens port 3306 on the container
   - '3306'
   # Where our data will be persisted
  networks:
      - sql_network 
  volumes:
   - my-db:/var/lib/mysql
 #Department Service
 department-service-container:
    image: department-service:1.1
    container_name: department-service-container
    build: department-service/.
    networks:
      - sql_network 
    ports:
      - '9000:9000'
    depends_on:
      - mysql-docker-container
    links:
      - mysql-docker-container:mysql-docker-container
#Networks       
networks:
    sql_network:   
# Names our volume
volumes:
  my-db:       


